apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-deployment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/venkatasv/aksvpatest.git'
    targetRevision: add-aks-workflow
    path: k8s/app-deployment
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd # Change this to your specific namespace if needed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
